/**
 * Step 4: translate `data/corpus/corpus.json` into `data/sql/seed.sql`.
 *
 * Full-text content is pre-stemmed here with the same code the Worker uses on
 * queries, which is what gives FTS5 French handling it does not have natively.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import type { Corpus } from "../src/domain/types.js";
import { stemText } from "../src/search/french.js";
import { CORPUS_FILE, SEED_FILE, SQL_DIR } from "./paths.js";

/** Rows per INSERT statement. D1 caps a single statement at 100 KB. */
const ROWS_PER_INSERT = 25;

function quote(value: string | number | null | undefined): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${value.replace(/'/g, "''")}'`;
}

/** Emits batched INSERTs, staying under the statement size limit. */
function insertStatements(table: string, columns: string[], rows: string[][]): string[] {
  const statements: string[] = [];
  for (let start = 0; start < rows.length; start += ROWS_PER_INSERT) {
    const batch = rows.slice(start, start + ROWS_PER_INSERT);
    const values = batch.map((row) => `  (${row.join(", ")})`).join(",\n");
    statements.push(`INSERT INTO ${table} (${columns.join(", ")}) VALUES\n${values};`);
  }
  return statements;
}

const corpus = JSON.parse(await readFile(CORPUS_FILE, "utf8")) as Corpus;
const headings = new Map(corpus.sections.map((section) => [section.id, section.heading]));

const statements: string[] = [
  "-- Generated by `npm run ingest:sql`. Do not edit by hand.",
  `-- Corpus ${corpus.corpusVersion}, generated ${corpus.generatedAt}.`,
  "",
];

statements.push(
  ...insertStatements(
    "corpus_meta",
    ["key", "value"],
    [
      [quote("corpus_version"), quote(corpus.corpusVersion)],
      [quote("generated_at"), quote(corpus.generatedAt)],
      [quote("election"), quote(corpus.election)],
      [quote("year"), quote(String(corpus.year))],
    ],
  ),
);

statements.push(
  ...insertStatements(
    "documents",
    [
      "id", "party", "election", "year", "title", "source_type",
      "source_url", "original_url", "collection", "imported_at", "checksum", "char_count",
    ],
    corpus.documents.map((document) => [
      quote(document.id),
      quote(document.party),
      quote(document.election),
      document.year,
      quote(document.title),
      quote(document.sourceType),
      quote(document.sourceUrl),
      quote(document.originalUrl ?? null),
      quote(document.collection ?? null),
      quote(document.importedAt),
      quote(document.checksum),
      document.charCount,
    ].map(String)),
  ),
);

statements.push(
  ...insertStatements(
    "sections",
    ["id", "document_id", "heading", "ord"],
    corpus.sections.map((section) => [
      quote(section.id),
      quote(section.documentId),
      quote(section.heading),
      String(section.order),
    ]),
  ),
);

statements.push(
  ...insertStatements(
    "chunks",
    ["id", "document_id", "section_id", "party", "text", "char_start", "char_end", "ord", "is_navigation"],
    corpus.chunks.map((chunk) => [
      quote(chunk.id),
      quote(chunk.documentId),
      quote(chunk.sectionId),
      quote(chunk.party),
      quote(chunk.text),
      String(chunk.charStart),
      String(chunk.charEnd),
      String(chunk.order),
      chunk.isNavigation ? "1" : "0",
    ]),
  ),
);

const topicRows = corpus.chunks.flatMap((chunk) =>
  chunk.topicTags.map((topic) => [quote(chunk.id), quote(topic)]),
);
statements.push(...insertStatements("chunk_topics", ["chunk_id", "topic"], topicRows));

statements.push(
  ...insertStatements(
    "chunks_fts",
    ["chunk_id", "stemmed_text", "stemmed_heading"],
    corpus.chunks.map((chunk) => [
      quote(chunk.id),
      quote(stemText(chunk.text)),
      quote(stemText(headings.get(chunk.sectionId) ?? "")),
    ]),
  ),
);

await mkdir(SQL_DIR, { recursive: true });
const sql = `${statements.join("\n")}\n`;
await writeFile(SEED_FILE, sql);

const longest = Math.max(...statements.map((statement) => statement.length));
console.log(
  `Seed written: ${corpus.documents.length} documents, ${corpus.sections.length} sections, ` +
    `${corpus.chunks.length} chunks, ${topicRows.length} tags\n` +
    `${statements.length} statements, ${(sql.length / 1024).toFixed(0)} KB, ` +
    `largest ${(longest / 1024).toFixed(1)} KB (D1 limit 100 KB)\n` +
    `-> ${SEED_FILE}`,
);

if (longest > 90 * 1024) {
  console.error("\nA statement is approaching the 100 KB limit: lower ROWS_PER_INSERT.");
  process.exit(1);
}
