/**
 * LFI's 2022 programmatic corpus, republished on melenchon2027.fr: 41 thematic
 * booklets and 13 detailed plans.
 *
 * They stand in for laec.fr, whose robots.txt is a search-engine allowlist closed
 * by `User-agent: * / Disallow: /`, putting the full book text out of reach of
 * automated retrieval. These booklets are the manifesto's detailed counterpart and
 * this host permits crawling. Inventory read from /wp-json/wp/v2/pages.
 */
export const LFI_PAGES: Array<[kind: string, path: string, id: string, title: string]> = [
  ["livrets-2022", "livrets-2022/agriculture-et-alimentation", "livrets-2022-agriculture-et-alimentation", "Agriculture et alimentation : Pour une agriculture écologique, qui nourrit la population et ceux qui en vivent"],
  ["livrets-2022", "livrets-2022/antiracisme", "livrets-2022-antiracisme", "Contre les discriminations : pour une république antiraciste"],
  ["livrets-2022", "livrets-2022/arts", "livrets-2022-arts", "Arts et culture : pour un service public du progrès humain"],
  ["livrets-2022", "livrets-2022/banques", "livrets-2022-banques", "Banques : pour un service public bancaire sous contrôle citoyen"],
  ["livrets-2022", "livrets-2022/condition-animale", "livrets-2022-condition-animale", "Condition animale : respecter les animaux c’est affirmer notre humanité"],
  ["livrets-2022", "livrets-2022/constituante", "livrets-2022-constituante", "Constituante : Pour une 6e République de l’intervention populaire"],
  ["livrets-2022", "livrets-2022/defense", "livrets-2022-defense", "Défense : une défense au service de la souveraineté populaire"],
  ["livrets-2022", "livrets-2022/droit-du-travail-uberisation", "livrets-2022-droit-du-travail-uberisation", "Droit du travail et ubérisation : pour la citoyenneté dans l’entreprise"],
  ["livrets-2022", "livrets-2022/eau-bien-commun", "livrets-2022-eau-bien-commun", "L’Eau, notre bien commun"],
  ["livrets-2022", "livrets-2022/economie-sociale-et-solidaire", "livrets-2022-economie-sociale-et-solidaire", "Économie sociale et solidaire : au cœur de la bifurcation écologique, sociale et solidaire de demain"],
  ["livrets-2022", "livrets-2022/education", "livrets-2022-education", "Éducation : reconstruire une école de l’égalité et de l’émancipation"],
  ["livrets-2022", "livrets-2022/egalite-femmes-hommes", "livrets-2022-egalite-femmes-hommes", "Égalité femmes-hommes : Vers une société féministe et émancipatrice"],
  ["livrets-2022", "livrets-2022/energie", "livrets-2022-energie", "100 % renouvelable : sortir des énergies fossiles et du nucléaire"],
  ["livrets-2022", "livrets-2022/enfance", "livrets-2022-enfance", "Enfance : garantir les droits des enfants"],
  ["livrets-2022", "livrets-2022/enseignement-superieur-et-recherche", "livrets-2022-enseignement-superieur-et-recherche", "Enseignement supérieur et recherche : Étudier, chercher et enseigner dans de bonnes conditions"],
  ["livrets-2022", "livrets-2022/espace", "livrets-2022-espace", "Espace : L’espace, notre horizon commun"],
  ["livrets-2022", "livrets-2022/foret", "livrets-2022-foret", "Forêt : respecter ce bien commun et ceux qui y travaillent"],
  ["livrets-2022", "livrets-2022/francais%c2%b7es-de-letranger", "livrets-2022-francaisc2b7es-de-letranger", "Français·es de l’étranger : nouveaux droits, nouvelles solidarités"],
  ["livrets-2022", "livrets-2022/francophonie", "livrets-2022-francophonie", "Francophonie : passer à la francophonie des peuples"],
  ["livrets-2022", "livrets-2022/handicap", "livrets-2022-handicap", "Handicap : Lever les obstacles à l’accès aux droits"],
  ["livrets-2022", "livrets-2022/jeunesse", "livrets-2022-jeunesse", "Jeunesse : Construire l’autonomie des jeunes"],
  ["livrets-2022", "livrets-2022/justice", "livrets-2022-justice", "Justice : Une justice au nom du peuple : garantir le service public de la justice et les libertés"],
  ["livrets-2022", "livrets-2022/laicite", "livrets-2022-laicite", "Laïcité : une République laïque"],
  ["livrets-2022", "livrets-2022/lgbti", "livrets-2022-lgbti", "Droits nouveaux et LGBTI : de nouvelles conquêtes pour l’égalité"],
  ["livrets-2022", "livrets-2022/logement", "livrets-2022-logement", "Logement : garantir le droit au logement"],
  ["livrets-2022", "livrets-2022/medias", "livrets-2022-medias", "Médias : l'information un bien commun"],
  ["livrets-2022", "livrets-2022/mer", "livrets-2022-mer", "Mer : La mer, nouvelle frontière de l’humanité"],
  ["livrets-2022", "livrets-2022/migrations", "livrets-2022-migrations", "Migrations : pour une politique migratoire humaniste et réaliste"],
  ["livrets-2022", "livrets-2022/numerique", "livrets-2022-numerique", "Numérique : notre révolution numérique"],
  ["livrets-2022", "livrets-2022/outre-mer", "livrets-2022-outre-mer", "Les Outre-mer à l’avant-garde de la bifurcation écologique et du progrès social"],
  ["livrets-2022", "livrets-2022/paix", "livrets-2022-paix", "Paix : pour une France indépendante, souveraine et non-alignée"],
  ["livrets-2022", "livrets-2022/planification-ecologique", "livrets-2022-planification-ecologique", "La planification écologique : La règle verte pour rompre avec le productivisme"],
  ["livrets-2022", "livrets-2022/plein-emploi", "livrets-2022-plein-emploi", "Plein emploi : Travailler moins, travailler mieux, travailler toutes et tous"],
  ["livrets-2022", "livrets-2022/quartiers-populaires", "livrets-2022-quartiers-populaires", "Quartiers populaires : l’égalité républicaine jusqu’au bout"],
  ["livrets-2022", "livrets-2022/retraites", "livrets-2022-retraites", "Retraites – Vieillir et bien vivre : Construire un service public de la dépendance"],
  ["livrets-2022", "livrets-2022/ruralite", "livrets-2022-ruralite", "Ruralité : garantir l’égalité républicaine"],
  ["livrets-2022", "livrets-2022/sante", "livrets-2022-sante", "Santé : Soigner le système de santé pour notre bien commun"],
  ["livrets-2022", "livrets-2022/securite-et-surete", "livrets-2022-securite-et-surete", "Sécurité et sûreté : Refonder le service public de la police"],
  ["livrets-2022", "livrets-2022/sport", "livrets-2022-sport", "Sport : Un sport émancipateur au service de l’humain"],
  ["livrets-2022", "livrets-2022/transports", "livrets-2022-transports", "Transports : Pour des mobilités durables et accessibles"],
  ["livrets-2022", "livrets-2022/zero-dechet", "livrets-2022-zero-dechet", "Zéro déchet : produire autrement pour consommer autrement"],
  ["plans-2022", "plans-2022/6e-republique", "plans-2022-6e-republique", "Comment nous allons passer à la 6e République"],
  ["plans-2022", "plans-2022/alimentation", "plans-2022-alimentation", "Comment nous allons : bien nourrir tout le monde"],
  ["plans-2022", "plans-2022/europe", "plans-2022-europe", "Notre stratégie en Europe : appliquer notre programme quoi qu'il en coûte"],
  ["plans-2022", "plans-2022/feminicides", "plans-2022-feminicides", "Comment nous allons mettre fin aux féminicides"],
  ["plans-2022", "plans-2022/justice-fiscale", "plans-2022-justice-fiscale", "Comment nous allons faire la justice fiscale"],
  ["plans-2022", "plans-2022/outre-mer", "plans-2022-outre-mer", "Comment nous allons : faire des Outre-mer les avant-postes du progrès humain"],
  ["plans-2022", "plans-2022/pauvrete", "plans-2022-pauvrete", "Comment nous allons éradiquer la pauvreté"],
  ["plans-2022", "plans-2022/plein-emploi", "plans-2022-plein-emploi", "Comment nous allons : atteindre le plein emploi"],
  ["plans-2022", "plans-2022/pouvoir-dachat", "plans-2022-pouvoir-dachat", "Comment nous allons : permettre à chacun de subvenir à ses besoins essentiels"],
  ["plans-2022", "plans-2022/qualifications", "plans-2022-qualifications", "Comment nous allons : produire les qualifications et savoirs nécessaires à la bifurcation écologique"],
  ["plans-2022", "plans-2022/regle-verte", "plans-2022-regle-verte", "Comment nous allons : mettre en œuvre la règle verte par la planification écologique"],
  ["plans-2022", "plans-2022/relocalisation", "plans-2022-relocalisation", "Relocalisation : produire ce dont la France a besoin"],
  ["plans-2022", "plans-2022/zero-sans-abri", "plans-2022-zero-sans-abri", "Comment nous allons : passer à zéro sans-abri"],
];
